### ISSUE TITLE
你好，请问有更新吗？刚测试qx不行呃。

### ISSUE THREAD

**Issue by LevineWoo** [vierzhuzhe/QX-MapStoryM-JS#1]
已经按你的说明配置了的。是不是我哪里操作有问题呢？

**Comment by vierzhuzhe** [comment]
我已经很久没玩这个游戏了😂。
https://github.com/MapleRen/MapleStoryM-language
这里面有大佬做的配置，你可以试一下。

əuıʌəl ***@***.***> 于2021年7月8日周四 下午10:34写道：
